backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Main Content"
        name: "sitte"      
        file: "content/site.json"
        fields:
          
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Booking URL", name: "bookingUrl", widget: "string" }
          - { label: "Business Name", name: "businessName", widget: "string" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
